package org.me.gcu.dramwise.data;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;

import java.util.List;

/**
 * Data Access Object (DAO) for interacting with the drink_entries table.
 * Provides insert operations, summary queries, and time‑based analytics
 * used throughout the app (e.g., charts, weekly totals, history lists).
 */
@Dao
public interface DrinkDao {

    /**
     * Inserts a new DrinkEntry into the database.
     *
     * @param entry The drink record to insert.
     * @return The autogenerated row ID of the inserted entry.
     */
    @Insert
    long insert(DrinkEntry entry);

    /**
     * Retrieves all drink entries ordered from newest to oldest.
     * Returned as LiveData so UI updates automatically when data changes.
     */
    @Query("SELECT * FROM drink_entries ORDER BY timestamp DESC")
    LiveData<List<DrinkEntry>> getAll();

    /**
     * Counts how many drink entries fall within a given time range.
     *
     * @param startMillis Start of the range (inclusive), in epoch millis.
     * @param endMillis   End of the range (inclusive), in epoch millis.
     */
    @Query("SELECT COUNT(*) FROM drink_entries WHERE timestamp BETWEEN :startMillis AND :endMillis")
    LiveData<Integer> countBetween(long startMillis, long endMillis);

    /**
     * Sums the total alcohol units consumed within a given time range.
     * COALESCE ensures the result is 0 instead of null when no rows match.
     */
    @Query("SELECT COALESCE(SUM(units), 0) FROM drink_entries WHERE timestamp BETWEEN :startMillis AND :endMillis")
    LiveData<Double> sumUnitsBetween(long startMillis, long endMillis);

    /**
     * Returns daily totals of alcohol units for the last 7 days (or any
     * period defined by startTime). The timestamp is converted from millis
     * to a local-date string using SQLite's date() function.
     *
     * Output is mapped into DailyUnits objects.
     *
     * @param startTime Epoch millis marking the earliest timestamp to include.
     */
    @Query(
            "SELECT " +
                    "date(timestamp / 1000, 'unixepoch', 'localtime') AS day, " +
                    "COALESCE(SUM(units), 0) AS totalUnits " +
                    "FROM drink_entries " +
                    "WHERE timestamp >= :startTime " +
                    "GROUP BY date(timestamp / 1000, 'unixepoch', 'localtime') " +
                    "ORDER BY day ASC"
    )
    LiveData<List<DailyUnits>> getUnitsLast7Days(long startTime);

    /**
     * Deletes all drink entries from the table.
     * Useful for debugging, resets, or clearing user data.
     */
    @Query("DELETE FROM drink_entries")
    void deleteAll();
}