plugins {
    // Applies the Android application plugin using the version catalog alias
    alias(libs.plugins.android.application)
}

android {
    // Package namespace for generated R classes and manifest
    namespace = "org.me.gcu.dramwise"

    // Android API level used to compile the project
    compileSdk = 36

    defaultConfig {
        // Unique application identifier
        applicationId = "org.me.gcu.dramwise"

        // Minimum Android version the app supports
        minSdk = 26

        // Target Android version the app is optimized for
        targetSdk = 36

        // Internal versioning for Play Store updates
        versionCode = 1

        // Human‑readable version name
        versionName = "1.0"

        // Test runner for instrumentation tests
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // Disables code shrinking/obfuscation for release builds
            isMinifyEnabled = false

            // ProGuard/R8 configuration files for release builds
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        // Java language level for source code
        sourceCompatibility = JavaVersion.VERSION_11

        // Java language level for generated bytecode
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildFeatures {
        // Enables ViewBinding for type‑safe view access
        viewBinding = true
    }
}

dependencies {
    // Core AndroidX + Material dependencies from version catalog
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.activity)
    implementation(libs.constraintlayout)

    // AndroidX Navigation components (Fragment + UI helpers)
    implementation("androidx.navigation:navigation-fragment:2.7.7")
    implementation("androidx.navigation:navigation-ui:2.7.7")

    // Room database runtime + annotation processor for DAO generation
    implementation("androidx.room:room-runtime:2.6.1")
    annotationProcessor("androidx.room:room-compiler:2.6.1")

    // Lifecycle components: runtime, LiveData, ViewModel
    implementation("androidx.lifecycle:lifecycle-runtime:2.8.7")
    implementation("androidx.lifecycle:lifecycle-livedata:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel:2.8.7")

    // MPAndroidChart library for charts/graphs
    implementation("com.github.PhilJay:MPAndroidChart:v3.1.0")

    // Unit testing
    testImplementation(libs.junit)

    // Android instrumentation testing
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
}